-- Notifications table for autonomous agent updates and system alerts
-- This table stores notifications generated by background agents and other system events

CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- 'agent_complete', 'digest_ready', 'error', 'info'
    title VARCHAR(255) NOT NULL,
    message TEXT,
    priority VARCHAR(20) DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    data JSONB DEFAULT '{}', -- Additional data like topicId, findingsCount, etc.
    read_at TIMESTAMP WITH TIME ZONE,
    dismissed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for efficient querying
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(user_id, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX idx_notifications_type ON notifications(type);

-- Update agents table to support autonomous execution
ALTER TABLE agents
ADD COLUMN IF NOT EXISTS parameters JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS error TEXT,
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'running', 'error', 'disabled'));

-- Add index for scheduler queries
CREATE INDEX IF NOT EXISTS idx_agents_due_for_run
ON agents(next_run)
WHERE enabled = true AND next_run IS NOT NULL;

-- Add auto-refresh settings to topics
ALTER TABLE topics
ADD COLUMN IF NOT EXISTS auto_refresh BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS refresh_frequency VARCHAR(20) DEFAULT 'daily' CHECK (refresh_frequency IN ('hourly', 'daily', 'weekly', 'monthly', 'manual'));

-- Track autonomous agent executions
CREATE TABLE IF NOT EXISTS agent_executions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    topic_id UUID REFERENCES topics(id) ON DELETE CASCADE,
    execution_type VARCHAR(20) NOT NULL CHECK (execution_type IN ('manual', 'scheduled', 'autonomous')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    findings_count INTEGER DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    duration_ms INTEGER -- Execution time in milliseconds
);

CREATE INDEX idx_agent_executions_agent_id ON agent_executions(agent_id);
CREATE INDEX idx_agent_executions_started_at ON agent_executions(started_at DESC);