/**
 * DigestPanel - Container component for digest display and generation
 *
 * Phase 3 Component Decomposition: Extracted from FindingsViewerProgressive.tsx
 *
 * This is a CONTAINER component - it connects to Zustand stores.
 * Uses useDigest() hook for digest data and generation.
 */

import { useDigest } from '@/hooks/useDigest';
import { useFindings } from '@/hooks/useFindings';
import { useAppStore } from '@/stores/appStore';
import { DigestProgress } from './DigestProgress';
import { DigestActions } from './DigestActions';
import { DigestCard } from '@/components/DigestCard';
import { Card, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Brain, Info, Sparkles } from 'lucide-react';
import { DigestTOC } from './DigestTOC';

// ============================================
// Types
// ============================================

interface DigestPanelProps {
  /** Topic ID to load digest for */
  topicId: string | null;
  /** Callback when "View Sources" is clicked */
  onViewSources: () => void;
  /** Callback when a finding is clicked in digest */
  onViewFinding?: (findingId: string) => void;
}

// ============================================
// Component
// ============================================

export function DigestPanel({ topicId, onViewSources, onViewFinding }: DigestPanelProps) {
  const {
    digest,
    isLoading,
    isGenerating,
    progress,
    message,
    generateDigest
  } = useDigest(topicId);

  const { findings } = useFindings(topicId);
  const { explanationMode, setExplanationMode } = useAppStore();

  const handleGenerate = () => {
    generateDigest(true); // force=true to bypass autoGenerateDigest check
  };

  // Show progress during generation
  if (isGenerating) {
    return (
      <Card className="p-8 text-center">
        <Sparkles className="h-12 w-12 mx-auto mb-4 text-primary animate-pulse" />
        <CardTitle className="mb-2">Generating AI-Powered Insights</CardTitle>
        <p className="text-[var(--color-text-muted)] mb-4">
          Analyzing {findings.length} findings to create your personalized digest...
        </p>
        <Progress value={progress} className="max-w-xs mx-auto" />
        <p className="text-xs text-[var(--color-text-muted)] mt-2">{message || 'Processing...'}</p>
      </Card>
    );
  }

  // PHASE 0 FIX: Show brief loading while checking queue status
  // This prevents "Ready to Generate" flash during queue check
  if (isLoading && !digest && !isGenerating) {
    return (
      <Card className="p-8 text-center">
        <Sparkles className="h-12 w-12 mx-auto mb-4 text-[var(--color-text-muted)] animate-pulse" />
        <p className="text-[var(--color-text-muted)]">Loading digest...</p>
      </Card>
    );
  }

  // Show digest if available
  if (digest && !isLoading) {
    return (
      <div className="flex gap-6">
        {/* TOC Sidebar — visible only on xl (1280px+) */}
        <aside className="hidden xl:block w-52 shrink-0">
          <DigestTOC digest={digest} onViewSources={onViewSources} />
        </aside>

        {/* Digest Content */}
        <div className="flex-1 min-w-0 space-y-4">
          <DigestCard
            digest={digest}
            explanationMode={explanationMode}
            setExplanationMode={setExplanationMode}
            onViewSources={onViewSources}
            onViewFinding={onViewFinding}
          />
          <DigestActions
            canGenerate={findings.length > 0}
            isGenerating={isGenerating}
            hasDigest={true}
            onGenerate={handleGenerate}
            findingsCount={findings.length}
          />
        </div>
      </div>
    );
  }

  // Show generate button when no digest exists
  if (!isLoading && findings.length > 0) {
    return (
      <Card className="p-8 text-center">
        <div className="space-y-4">
          <div className="relative inline-block">
            <Brain className="h-16 w-16 mx-auto text-primary/30" />
            <Info className="h-6 w-6 text-primary absolute -top-1 -right-1 animate-bounce" />
          </div>
          <div className="text-center space-y-2">
            <CardTitle className="text-xl">Ready to Generate Insights</CardTitle>
            <p className="text-[var(--color-text-muted)] max-w-md mx-auto">
              Transform your {findings.length} research findings into an AI-powered digest
              with breakthroughs and actionable insights.
            </p>
          </div>
          <DigestActions
            canGenerate={findings.length > 0}
            isGenerating={isGenerating}
            hasDigest={false}
            onGenerate={handleGenerate}
            findingsCount={findings.length}
          />
        </div>
      </Card>
    );
  }

  // Loading or no data
  return null;
}
