/**
 * DigestPanel - Container component for digest display and generation
 *
 * Phase 3 Component Decomposition: Extracted from FindingsViewerProgressive.tsx
 *
 * This is a CONTAINER component - it connects to Zustand stores.
 * Uses useDigest() hook for digest data and generation.
 */

import { useDigest } from '@/hooks/useDigest';
import { useFindings } from '@/hooks/useFindings';
import { useAppStore } from '@/stores/appStore';
import { DigestProgress } from './DigestProgress';
import { DigestActions } from './DigestActions';
import { DigestCard } from '@/components/DigestCard';
import { Card, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Brain, Info, Sparkles } from 'lucide-react';

// ============================================
// Types
// ============================================

interface DigestPanelProps {
  /** Topic ID to load digest for */
  topicId: string | null;
  /** Callback when "View Sources" is clicked */
  onViewSources: () => void;
  /** Callback when a theme is clicked */
  onThemeClick: (themeId: string, themeName: string) => void;
}

// ============================================
// Component
// ============================================

export function DigestPanel({ topicId, onViewSources, onThemeClick }: DigestPanelProps) {
  const {
    digest,
    timeframe,
    isLoading,
    isGenerating,
    progress,
    message,
    generateDigest,
    refreshDigest
  } = useDigest(topicId);

  const { findings } = useFindings(topicId);
  const { explanationMode, setExplanationMode } = useAppStore();

  // Get filtered findings count for current timeframe
  const filteredFindingsCount = (() => {
    const now = Date.now();
    const day = 24 * 60 * 60 * 1000;

    switch (timeframe) {
      case 'daily':
        return findings.filter(f => f.timestamp > now - day).length;
      case 'weekly':
        return findings.filter(f => f.timestamp > now - (7 * day)).length;
      case 'monthly':
        return findings.filter(f => f.timestamp > now - (30 * day)).length;
      default:
        return findings.length;
    }
  })();

  const handleGenerate = () => {
    generateDigest(true); // force=true to bypass autoGenerateDigest check
  };

  const handleRefresh = () => {
    refreshDigest();
  };

  const handleThemeClick = (themeId: string) => {
    const theme = digest?.themes?.find(t => t.id === themeId);
    onThemeClick(themeId, theme?.name || '');
  };

  // Show progress during generation
  if (isGenerating) {
    return (
      <Card className="p-8 text-center">
        <Sparkles className="h-12 w-12 mx-auto mb-4 text-primary animate-pulse" />
        <CardTitle className="mb-2">Generating AI-Powered Insights</CardTitle>
        <p className="text-muted-foreground mb-4">
          Analyzing {filteredFindingsCount} findings to create your personalized digest...
        </p>
        <Progress value={progress} className="max-w-xs mx-auto" />
        <p className="text-xs text-muted-foreground mt-2">{message || 'Processing...'}</p>
      </Card>
    );
  }

  // PHASE 0 FIX: Show brief loading while checking queue status
  // This prevents "Ready to Generate" flash during queue check
  if (isLoading && !digest && !isGenerating) {
    return (
      <Card className="p-8 text-center">
        <Sparkles className="h-12 w-12 mx-auto mb-4 text-muted-foreground animate-pulse" />
        <p className="text-muted-foreground">Loading digest...</p>
      </Card>
    );
  }

  // Show digest if available
  if (digest && !isLoading) {
    return (
      <div className="space-y-4">
        <DigestCard
          digest={digest}
          explanationMode={explanationMode}
          setExplanationMode={setExplanationMode}
          onThemeClick={handleThemeClick}
          onViewSources={onViewSources}
        />
        <DigestActions
          canGenerate={filteredFindingsCount > 0}
          isGenerating={isGenerating}
          hasDigest={true}
          onGenerate={handleGenerate}
          onRefresh={handleRefresh}
          findingsCount={filteredFindingsCount}
        />
      </div>
    );
  }

  // Show generate button when no digest exists
  if (!isLoading && findings.length > 0) {
    return (
      <Card className="p-8 text-center">
        <div className="space-y-4">
          <div className="relative inline-block">
            <Brain className="h-16 w-16 mx-auto text-primary/30" />
            <Info className="h-6 w-6 text-primary absolute -top-1 -right-1 animate-bounce" />
          </div>
          <div className="text-center space-y-2">
            <CardTitle className="text-xl">Ready to Generate Insights</CardTitle>
            <p className="text-muted-foreground max-w-md mx-auto">
              Transform your {filteredFindingsCount} research findings into an AI-powered digest
              with key themes, breakthroughs, and actionable insights.
            </p>
          </div>
          <DigestActions
            canGenerate={filteredFindingsCount > 0}
            isGenerating={isGenerating}
            hasDigest={false}
            onGenerate={handleGenerate}
            onRefresh={handleRefresh}
            findingsCount={filteredFindingsCount}
          />
        </div>
      </Card>
    );
  }

  // Loading or no data
  return null;
}
