/**
 * useDigest - Hook for digest data and generation
 *
 * Phase 2 Refactoring: Wraps researchStore, uiStore, and appStore for digest management.
 *
 * Key principles:
 * 1. Single source of truth from researchStore
 * 2. Loading/progress state from uiStore (centralized)
 * 3. Timeframe preference from appStore
 * 4. Generation is gated by autoGenerateDigest setting
 * 5. No useState - all state comes from stores
 *
 * This hook is critical for fixing the race condition issues that caused
 * Issue 17 (auto-generation causing "Generating AI-Powered Insights" on every page load).
 *
 * Usage:
 * ```typescript
 * function DigestView({ topicId }) {
 *   const {
 *     digest,
 *     isLoading,
 *     isGenerating,
 *     progress,
 *     generateDigest
 *   } = useDigest(topicId);
 *
 *   return (
 *     <div>
 *       {isGenerating && <ProgressBar value={progress} />}
 *       {digest && <DigestCard digest={digest} />}
 *       <button onClick={() => generateDigest()}>Generate</button>
 *     </div>
 *   );
 * }
 * ```
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { useResearchStore } from '@/stores/researchStore';
import { useUIStore } from '@/stores/uiStore';
import { useAppStore } from '@/stores/appStore';
import { digestService } from '@/services/digest.service';
import { logger } from '@/utils/logger';
import type { SmartDigest, DigestTimeframe } from '@/types';

interface UseDigestReturn {
  // Data
  digest: SmartDigest | null;
  timeframe: DigestTimeframe;

  // Loading states
  isLoading: boolean;
  isGenerating: boolean;
  progress: number;
  message: string;

  // Actions
  loadDigest: () => Promise<void>;
  generateDigest: (force?: boolean) => Promise<void>;
  refreshDigest: () => Promise<void>;
  clearDigest: () => void;
  setTimeframe: (timeframe: DigestTimeframe) => void;
}

/**
 * Hook for managing digest for a specific topic.
 *
 * @param topicId - The topic ID to get/generate digest for (null for no topic)
 * @param timeframeOverride - Optional override for the timeframe (uses appStore preference if not provided)
 */
export function useDigest(
  topicId: string | null,
  timeframeOverride?: DigestTimeframe
): UseDigestReturn {
  // Get store state and actions
  const {
    getDigestForTopic,
    loadDigest: loadDigestFromStore,
    generateDigest: generateDigestFromStore,
    setDigest,
    clearDigest: clearDigestFromStore
  } = useResearchStore();

  const {
    loading,
    setLoading,
    digestProgress,
    digestMessage,
    setDigestProgress
  } = useUIStore();

  const {
    digestTimeframe: storedTimeframe,
    setDigestTimeframe,
    autoGenerateDigest
  } = useAppStore();

  // Use override if provided, otherwise use stored preference
  const timeframe = timeframeOverride ?? storedTimeframe;

  // Bumped when generateDigest() is called — forces the queue-polling useEffect to restart
  const [generationEpoch, setGenerationEpoch] = useState(0);

  // Get digest from store
  const digest = topicId ? getDigestForTopic(topicId, timeframe) : null;

  // Loading states
  const isLoading = loading.digest;
  const isGenerating = digestProgress > 0 && digestProgress < 100;

  /**
   * Load digest from cache/server (no generation)
   */
  const loadDigest = useCallback(async () => {
    if (!topicId) return;

    setLoading('digest', true);
    try {
      await loadDigestFromStore(topicId, timeframe);
    } finally {
      setLoading('digest', false);
    }
  }, [topicId, timeframe, loadDigestFromStore, setLoading]);

  /**
   * Generate a new digest.
   * This replaces the complex generation logic that was in the component.
   *
   * @param force - If true, generate even if autoGenerateDigest is false
   */
  const generateDigest = useCallback(async (force = false) => {
    if (!topicId) return;

    // Check if auto-generation is allowed (unless forced)
    if (!force && !autoGenerateDigest) {
      logger.debug('[useDigest] Auto-generation disabled, skipping');
      return;
    }

    // Prevent duplicate generation
    if (isGenerating) {
      logger.debug('[useDigest] Generation already in progress');
      return;
    }

    setLoading('digest', true);
    setDigestProgress(10, 'Queued for generation...');

    try {
      // Create the queue item — backend DigestProcessor handles the rest.
      // The useEffect queue-status poller (line ~271) will track progress
      // and load the digest when complete. No second polling loop needed.
      await digestService.queueDigestFromExistingFindings(
        topicId,
        timeframe
      );

      logger.debug('[useDigest] Queue item created, useEffect poller will track progress');

      // Bump epoch so the queue-polling useEffect restarts and picks up the new item
      setGenerationEpoch(prev => prev + 1);

    } catch (error) {
      logger.error('[useDigest] Error generating digest:', error);
      setDigestProgress(0, 'Generation failed');
      setLoading('digest', false);
    }
  }, [
    topicId,
    timeframe,
    autoGenerateDigest,
    isGenerating,
    setLoading,
    setDigestProgress
  ]);

  /**
   * Refresh digest - runs new research then generates digest
   * This is the "full refresh" that fetches new findings first.
   */
  const refreshDigest = useCallback(async () => {
    if (!topicId) return;

    setLoading('digest', true);
    setDigestProgress(0, 'Fetching new research...');

    try {
      // Use the integrated refresh method
      const queueItem = await digestService.refreshResearchAndDigest(
        topicId,
        timeframe,
        'high'
      );

      setDigestProgress(50, 'Generating digest...');

      // Load the refreshed digest
      await loadDigestFromStore(topicId, timeframe);

      setDigestProgress(100, 'Refresh complete!');

      setTimeout(() => {
        setDigestProgress(0, '');
        setLoading('digest', false);
      }, 1500);

    } catch (error) {
      logger.error('[useDigest] Error refreshing digest:', error);
      setDigestProgress(0, 'Refresh failed');
      setLoading('digest', false);
    }
  }, [topicId, timeframe, setLoading, setDigestProgress, loadDigestFromStore]);

  /**
   * Clear digest for this topic
   */
  const clearDigest = useCallback(() => {
    if (topicId) {
      clearDigestFromStore(topicId);
    }
  }, [topicId, clearDigestFromStore]);

  /**
   * Change the timeframe preference
   */
  const setTimeframe = useCallback((newTimeframe: DigestTimeframe) => {
    setDigestTimeframe(newTimeframe);
  }, [setDigestTimeframe]);

  /**
   * PHASE 0 FIX: Check for active digest queue on mount.
   * This ensures UI shows "Generating..." even if generation was started
   * elsewhere (scheduler, another page, after agent completion).
   */
  useEffect(() => {
    if (!topicId) return;

    let isMounted = true;
    let pollTimer: NodeJS.Timeout | null = null;
    let hasResolvedOnce = false;

    const checkQueueStatus = async () => {
      if (hasResolvedOnce || !isMounted) return;

      setLoading('digest', true);
      try {
        logger.debug(`[useDigest] Checking queue status for topic ${topicId}...`);
        const status = await digestService.getQueueStatusByTopic(topicId);

        if (!isMounted) return;

        if (status && (status.status === 'pending' || status.status === 'processing')) {
          // Active queue found! Show generation progress
          logger.debug(`[useDigest] Active queue found:`, status);
          const percentage = status.status === 'processing' ? 50 : 10;
          const message = status.status === 'processing'
            ? 'Generating digest...'
            : 'Queued for generation...';

          setDigestProgress(percentage, message);

          // Continue polling until complete
          pollTimer = setTimeout(checkQueueStatus, 2000);
        } else {
          // Queue resolved (completed, failed, or absent) — resolve once and stop
          hasResolvedOnce = true;

          if (status?.status === 'completed') {
            logger.debug(`[useDigest] Queue completed, loading digest...`);
          } else {
            logger.debug(`[useDigest] No active queue for topic ${topicId}, trying to load digest...`);
          }

          try {
            await loadDigestFromStore(topicId, timeframe);
          } catch (loadError) {
            logger.debug(`[useDigest] No digest found for topic ${topicId}`);
          }

          setDigestProgress(0, '');
          setLoading('digest', false);
        }
      } catch (error) {
        logger.error('[useDigest] Error checking queue status:', error);
        hasResolvedOnce = true;
        setDigestProgress(0, '');
        setLoading('digest', false);
      }
    };

    // Check immediately on mount
    checkQueueStatus();

    return () => {
      isMounted = false;
      if (pollTimer) clearTimeout(pollTimer);
    };
  }, [topicId, timeframe, generationEpoch, setDigestProgress, loadDigestFromStore, setLoading]);

  return {
    // Data
    digest,
    timeframe,

    // Loading states
    isLoading,
    isGenerating,
    progress: digestProgress,
    message: digestMessage,

    // Actions
    loadDigest,
    generateDigest,
    refreshDigest,
    clearDigest,
    setTimeframe
  };
}
