/**
 * App Store - Zustand state management for global application state
 *
 * Phase 2 Refactoring: Consolidates user, theme, and preferences
 *
 * Key principles:
 * 1. User authentication state (but not sensitive data)
 * 2. Theme and display preferences
 * 3. Digest and explanation mode preferences
 * 4. Auto-generation settings (critical for fixing race conditions)
 *
 * This store is FULLY PERSISTENT - all state survives page refresh.
 */

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import type { DigestTimeframe, ExplanationMode } from '@/types';

// ============================================
// Types
// ============================================

type Theme = 'light' | 'dark' | 'system';

export type FindingsDateFilter = 'all' | '7d' | '30d' | '90d';

interface UserInfo {
  id: string;
  name: string;
  email: string;
  avatar?: string;
}

interface AppStore {
  // ============================================
  // User & Auth
  // ============================================
  user: UserInfo | null;
  isAuthenticated: boolean;

  // ============================================
  // Theme
  // ============================================
  theme: Theme;

  // ============================================
  // Digest Preferences
  // ============================================
  digestTimeframe: DigestTimeframe;
  explanationMode: ExplanationMode;
  autoGenerateDigest: boolean;

  // ============================================
  // Feature Flags
  // ============================================
  enableAgentAutoRun: boolean;
  enableNotifications: boolean;
  enableAnalytics: boolean;

  // ============================================
  // Findings Date Filter
  // ============================================
  findingsDateFilter: FindingsDateFilter;

  // ============================================
  // Actions - User
  // ============================================
  setUser: (user: UserInfo | null) => void;
  updateUser: (updates: Partial<UserInfo>) => void;
  logout: () => void;

  // ============================================
  // Actions - Theme
  // ============================================
  setTheme: (theme: Theme) => void;
  toggleTheme: () => void;

  // ============================================
  // Actions - Preferences
  // ============================================
  setDigestTimeframe: (timeframe: DigestTimeframe) => void;
  setExplanationMode: (mode: ExplanationMode) => void;
  toggleAutoGenerate: () => void;
  setAutoGenerateDigest: (enabled: boolean) => void;

  // ============================================
  // Actions - Feature Flags
  // ============================================
  setEnableAgentAutoRun: (enabled: boolean) => void;
  setEnableNotifications: (enabled: boolean) => void;
  setEnableAnalytics: (enabled: boolean) => void;

  // ============================================
  // Actions - Findings Date Filter
  // ============================================
  setFindingsDateFilter: (filter: FindingsDateFilter) => void;

  // ============================================
  // Actions - Bulk
  // ============================================
  updatePreferences: (prefs: Partial<Pick<AppStore,
    'digestTimeframe' | 'explanationMode' | 'autoGenerateDigest' |
    'enableAgentAutoRun' | 'enableNotifications' | 'enableAnalytics' |
    'findingsDateFilter'
  >>) => void;

  reset: () => void;
}

// Dark mode handled by CSS @media (prefers-color-scheme: dark)
// No class toggling needed — Tailwind darkMode: 'media' uses native CSS
const applyTheme = (_theme: Theme) => {
  // Intentionally empty — CSS custom properties in index.css
  // handle light/dark via @media (prefers-color-scheme: dark)
};

export const useAppStore = create<AppStore>()(
  persist(
    (set, get) => ({
      // ============================================
      // Initial State
      // ============================================
      user: null,
      isAuthenticated: false,

      theme: 'system',

      digestTimeframe: 'weekly',
      explanationMode: 'technical',
      // IMPORTANT: Default to FALSE until race conditions are fully fixed
      // This was the root cause of Issue 17 - auto-generation causing
      // "Generating AI-Powered Insights" on every page load
      autoGenerateDigest: false,

      enableAgentAutoRun: false, // Also default to false until fixed
      enableNotifications: true,
      enableAnalytics: true,

      findingsDateFilter: 'all',

      // ============================================
      // User Actions
      // ============================================

      setUser: (user: UserInfo | null) => {
        set({
          user,
          isAuthenticated: !!user
        });
      },

      updateUser: (updates: Partial<UserInfo>) => {
        const { user } = get();
        if (user) {
          set({ user: { ...user, ...updates } });
        }
      },

      logout: () => {
        set({
          user: null,
          isAuthenticated: false
        });
        // Note: Should also clear researchStore and uiStore when logging out
        // This is done through the auth service, not here
      },

      // ============================================
      // Theme Actions
      // ============================================

      setTheme: (theme: Theme) => {
        set({ theme });
        applyTheme(theme);
      },

      toggleTheme: () => {
        const { theme } = get();
        const nextTheme: Theme = theme === 'light' ? 'dark' : 'light';
        set({ theme: nextTheme });
        applyTheme(nextTheme);
      },

      // ============================================
      // Preference Actions
      // ============================================

      setDigestTimeframe: (digestTimeframe: DigestTimeframe) => {
        set({ digestTimeframe });
      },

      setExplanationMode: (explanationMode: ExplanationMode) => {
        set({ explanationMode });
      },

      toggleAutoGenerate: () => {
        set(state => ({
          autoGenerateDigest: !state.autoGenerateDigest
        }));
      },

      setAutoGenerateDigest: (enabled: boolean) => {
        set({ autoGenerateDigest: enabled });
      },

      // ============================================
      // Feature Flag Actions
      // ============================================

      setEnableAgentAutoRun: (enabled: boolean) => {
        set({ enableAgentAutoRun: enabled });
      },

      setEnableNotifications: (enabled: boolean) => {
        set({ enableNotifications: enabled });
      },

      setEnableAnalytics: (enabled: boolean) => {
        set({ enableAnalytics: enabled });
      },

      // ============================================
      // Findings Date Filter Actions
      // ============================================

      setFindingsDateFilter: (findingsDateFilter: FindingsDateFilter) => {
        set({ findingsDateFilter });
      },

      // ============================================
      // Bulk Actions
      // ============================================

      updatePreferences: (prefs) => {
        set(prefs);
      },

      reset: () => {
        set({
          user: null,
          isAuthenticated: false,
          theme: 'system',
          digestTimeframe: 'weekly',
          explanationMode: 'technical',
          autoGenerateDigest: false,
          enableAgentAutoRun: false,
          enableNotifications: true,
          enableAnalytics: true,
          findingsDateFilter: 'all'
        });
        applyTheme('system');
      }
    }),
    {
      name: 'app-store',
      storage: createJSONStorage(() => localStorage),
      // Persist everything except user (user comes from auth service)
      partialize: (state) => ({
        theme: state.theme,
        digestTimeframe: state.digestTimeframe,
        explanationMode: state.explanationMode,
        autoGenerateDigest: state.autoGenerateDigest,
        enableAgentAutoRun: state.enableAgentAutoRun,
        enableNotifications: state.enableNotifications,
        enableAnalytics: state.enableAnalytics,
        findingsDateFilter: state.findingsDateFilter
      }),
      // Apply theme on hydration
      onRehydrateStorage: () => (state) => {
        if (state) {
          applyTheme(state.theme);
        }
      }
    }
  )
);
